from pathlib import Path
gbk = Path(f"ASCII_gbk.txt")
utf_8 = Path(f"ASCII_utf8.txt")
data = """ASCII0~126码表-by eoolife
说明:
0~31:控制字符
本文件完全由程序生成！
已开源在Github https://github.com/coukayouxi/python_ascill
-----
ASCII 0~126 code table - by eoolife
Instructions:
0~31: Control characters
This document is completely generated by a program!
It has been open sourced on Github at https://github.com/coukayouxi/python_ascill

"""
for i in range(0, 127): # 遍历ASCII码表 0-126
    if i == 10:
        data += f"{i}:LF,下移一行（光标垂直移动，不回到行首）\n"
        data += f"ENGLISH: Move down one line (move the cursor vertically without returning to the beginning of the line)\n"
        continue
    elif i == 13:
        data += f"{i}:CR,回到行首\n"
        data += f"ENGLISH: Return to the beginning of the line\n"
        continue
    data += f"{i}:'{chr(i)}'\n"
    

gbk.write_text(data, encoding='gbk')
utf_8.write_text(data, encoding='utf-8')